name: Cordova App CI Pipeline
run-name: ${{ github.actor }} have started the pipeline 🚀
on:
    push:
        branches:
            - main
jobs:
    build-web-app:
        name: Build website
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository to the runner
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21.x

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build the web app
              run: yarn build

    build-android-app:
        name: Build the Android app
        runs-on: ubuntu-latest
        needs: build-web-app
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21.x
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
            - name: Install necessary tools and Android platform
              run: sdkmanager "platform-tools" "platforms;android-33"

            - name: Setup Cordova
              run: yarn global add cordova

            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Install Cordova dependencies
              working-directory: cordova-app
              run: npm ci
            - name: Add Android platform
              working-directory: cordova-app
              run: |
                mkdir -p www
                cordova platform add android

            - name: Check Cordova requirements
              working-directory: cordova-app
              run: cordova requirements

            - name: Build the Apk
              run: yarn cordova-build
