name: Cordova App CI Pipeline
run-name: ${{ github.actor }} have started the pipeline 🚀
on:
  push:
    branches:
      - main
jobs:
  build-web-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the web app
        run: yarn build
