name: Cordova App CI Pipeline
run-name: 🚀 ${{ github.actor }} have started the pipeline
on:
    push:
        branches:
            - main

env:
    VERSION_NODE: 21.x
    VERSION_JAVA: "17"

jobs:
    build-web-app:
        name: Build website
        runs-on: ubuntu-latest
        steps:
            - name: Check repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.VERSION_NODE }}

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build the web app
              run: yarn build

            - name: Store static webpages
              uses: actions/upload-artifact@v4
              with:
                  name: webapp-static-pages
                  retention-days: 1
                  path: dist

    build-android-app:
        name: Build the Android app
        runs-on: ubuntu-latest
        needs: build-web-app
        defaults:
            run:
                working-directory: cordova-app
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.VERSION_NODE }}
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: ${{ env.VERSION_JAVA }}
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
            - name: Install necessary tools and Android target platforms
              run: sdkmanager "platform-tools" "platforms;android-33"

            - name: Install Cordova
              run: npm install -g cordova

            - name: Install Cordova dependencies
              run: npm ci
            - name: Add Android platform
              run: |
                  mkdir -p www
                  cordova platform add android

            - name: Get static webpages
              uses: actions/download-artifact@v4
              with:
                  name: webapp-static-pages
                  path: cordova-app/www

            - name: Build the APK
              run: cordova build android

            - name: Publish the APK
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: cordova-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
